name: tutuaword
description: AI-native document editor — Flutter UI shell
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  file_picker: ^8.1.2
  path: ^1.9.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
